/**
 * FitCheck - Canonical Data Model
 * 
 * Technical Principles:
 * - TypeScript strict mode.
 * - One canonical room model shared by 2D planner and 3D viewer.
 * - Centimeters (cm) as canonical units for all internal geometric calculations.
 * - Every dimension and item records provenance and confirmation status.
 * - Zero external AI calls without explicit consent.
 */

export type UnitType = 'cm' | 'm' | 'in' | 'ft';

export type DimensionProvenance = 
  | 'manual'         // Entered by user manually
  | 'catalog'        // From verified manufacturer/catalog specs
  | 'photo-estimate' // Derived from room photo analysis (uncertain)
  | 'ai-suggestion'; // Generated by AI inference (unconfirmed until verified)

export interface ClearanceRequirements {
  front?: number; // cm needed in front (e.g. drawer pullout, sofa legroom)
  back?: number;  // cm needed behind (e.g. cable access, airflow)
  left?: number;  // cm needed on left
  right?: number; // cm needed on right
  notes?: string;
}

export interface FurnitureItem {
  id: string;
  name: string;
  category: 
    | 'seating' 
    | 'table' 
    | 'bed' 
    | 'storage' 
    | 'desk' 
    | 'lighting' 
    | 'decor' 
    | 'other';
  
  // Canonical dimensions in centimeters (cm)
  width: number;  // local X dimension in cm
  depth: number;  // local Y dimension in cm
  height: number; // local Z dimension in cm

  // Position in room coordinates (cm)
  // Origin (0,0) is top-left of the room rectangle (or center if aligned)
  x: number; // cm from left wall (West wall)
  y: number; // cm from top wall (North wall)
  z: number; // cm elevation above floor (default 0)
  
  // Rotation around Z-axis in degrees (0 - 359)
  rotation: number;

  color: string;
  modelType: string; // for 3D procedural generation e.g. 'sofa_3seater', 'bed_queen', 'dining_table'

  clearances: ClearanceRequirements;

  // Provenance & Confirmation Tracking
  provenance: DimensionProvenance;
  isConfirmed: boolean;
  confidence?: number; // 0.0 - 1.0 (for photo or AI estimates)
  provenanceNotes?: string;
  
  // Optional catalog metadata
  catalogId?: string;
  price?: number;
  sku?: string;
}

export type WallSide = 'north' | 'south' | 'east' | 'west';

export type DoorSwing = 
  | 'inward-left' 
  | 'inward-right' 
  | 'outward-left' 
  | 'outward-right' 
  | 'sliding' 
  | 'none';

export interface RoomOpening {
  id: string;
  type: 'door' | 'window' | 'radiator' | 'opening';
  wall: WallSide;
  offset: number; // cm from wall's start corner (clockwise: North start at top-left, East start at top-right, etc.)
  width: number;  // cm
  height: number; // cm
  sillHeight?: number; // cm from floor (for windows)
  doorSwing?: DoorSwing;
  swingClearance?: number; // cm radius of swing arc (defaults to door width)
}

export interface RoomModel {
  name: string;
  width: number;   // cm (X dimension, West-to-East)
  length: number;  // cm (Y dimension, North-to-South)
  height: number;  // cm (Z dimension, floor to ceiling)
  wallThickness: number; // cm (default 15cm)
  openings: RoomOpening[];
}

export interface PhotoDetectionSuggestion {
  id: string;
  label: string;
  category: FurnitureItem['category'];
  estimatedWidth: number;  // cm
  estimatedDepth: number;  // cm
  estimatedHeight: number; // cm
  suggestedX: number;      // cm
  suggestedY: number;      // cm
  rotation: number;        // degrees
  confidence: number;      // 0.0 - 1.0
  color: string;
  modelType: string;
  box2D?: {
    x: number;      // normalized 0..1 in photo
    y: number;
    width: number;
    height: number;
  };
  notes?: string;
}

export interface PhotoContext {
  hasPhoto: boolean;
  photoDataUrl?: string; // Stored locally only, never transmitted
  photoName?: string;
  uploadedAt?: string;
  imageDimensions?: { width: number; height: number };
  detectedSuggestions?: PhotoDetectionSuggestion[];
  privacyConsentAcknowledged: boolean;
}

export interface AppSettings {
  displayUnit: UnitType;
  gridSnap: boolean;
  gridSnapSizeCm: number; // e.g., 5 or 10 cm
  showClearanceZones: boolean;
  showDimensionsOnPlan: boolean;
  enableExternalAi: boolean; // Explicit user opt-in required
  aiProvider: 'local-heuristic' | 'custom-gemini-key' | 'disabled';
  customAiApiKey?: string;
}

export interface FitProject {
  id: string;
  name: string;
  createdAt: string;
  updatedAt: string;
  room: RoomModel;
  furniture: FurnitureItem[];
  photoContext: PhotoContext;
  settings: AppSettings;
}

// Fit-report semantics (strict adherence to requirements)
export type FitStatus = 'PASS' | 'FAIL' | 'REVIEW' | 'NOT_CHECKED';

export type CheckCategory = 
  | 'room-boundary'
  | 'furniture-collision'
  | 'door-clearance'
  | 'functional-clearance'
  | 'measurement-confidence';

export interface FitCheckItem {
  id: string;
  title: string;
  description: string;
  category: CheckCategory;
  status: FitStatus;
  affectedItemIds: string[];
  severity: 'error' | 'warning' | 'info';
  details?: string;
  remedyRecommendation?: string;
}

export interface FitReport {
  overallStatus: FitStatus;
  generatedAt: string;
  summary: {
    passCount: number;
    failCount: number;
    reviewCount: number;
    notCheckedCount: number;
  };
  checks: FitCheckItem[];
  disclaimer: string;
}

export const MANDATORY_FIT_DISCLAIMER = 
  "Passing a room geometry check does not guarantee successful delivery, " +
  "installation, structural safety, or compliance with building codes. " +
  "Always measure physical delivery paths (stairwells, doorways, elevators) " +
  "and consult a professional for structural or safety modifications.";
