/**
 * ApnaGhar (अपना घर) - Canonical Data Model
 * 
 * Technical Principles:
 * - TypeScript strict mode.
 * - One canonical home and room model shared by 2D planner, 3D visualizer, and fit engine.
 * - Centimeters (cm) as canonical units for all internal geometric calculations.
 * - Multi-floor and multi-room project hierarchy with backward compatibility.
 * - Every dimension and item records provenance and confirmation status.
 * - Interior styling: materials, finishes, and design alternatives.
 * - Local-first persistence and zero external AI calls without explicit consent.
 */

export type UnitType = 'cm' | 'm' | 'in' | 'ft';

export type DimensionProvenance = 
  | 'manual'         // Entered by user manually
  | 'catalog'        // From verified manufacturer/catalog specs
  | 'photo-estimate' // Derived from room photo analysis (uncertain)
  | 'ai-suggestion'; // Generated by AI inference (unconfirmed until verified)

export interface ClearanceRequirements {
  front?: number; // cm needed in front (e.g. drawer pullout, sofa legroom)
  back?: number;  // cm needed behind (e.g. cable access, airflow)
  left?: number;  // cm needed on left
  right?: number; // cm needed on right
  notes?: string;
}

export interface FurnitureItem {
  id: string;
  name: string;
  category: 
    | 'seating' 
    | 'table' 
    | 'bed' 
    | 'storage' 
    | 'desk' 
    | 'lighting' 
    | 'decor' 
    | 'other';
  
  // Canonical dimensions in centimeters (cm)
  width: number;  // local X dimension in cm
  depth: number;  // local Y dimension in cm
  height: number; // local Z dimension in cm

  // Position in room coordinates (cm)
  // Origin (0,0) is top-left of the room rectangle
  x: number; // cm from left wall (West wall)
  y: number; // cm from top wall (North wall)
  z: number; // cm elevation above floor (default 0)
  
  // Rotation around Z-axis in degrees (0 - 359)
  rotation: number;

  color: string;
  material?: string; // e.g., 'natural_oak', 'walnut', 'boucle_fabric', 'linen', 'matte_black', 'brass'
  modelType: string; // for 3D procedural generation e.g. 'sofa_3seater', 'bed_queen', 'dining_table'

  clearances: ClearanceRequirements;

  // Provenance & Confirmation Tracking
  provenance: DimensionProvenance;
  isConfirmed: boolean;
  confidence?: number; // 0.0 - 1.0 (for photo or AI estimates)
  provenanceNotes?: string;
  
  // Optional catalog metadata
  catalogId?: string;
  price?: number;
  sku?: string;
}

export type WallSide = 'north' | 'south' | 'east' | 'west';

export type DoorSwing = 
  | 'inward-left' 
  | 'inward-right' 
  | 'outward-left' 
  | 'outward-right' 
  | 'sliding' 
  | 'none';

export interface RoomOpening {
  id: string;
  type: 'door' | 'window' | 'radiator' | 'opening';
  wall: WallSide;
  offset: number; // cm from wall's start corner (clockwise: North start at top-left, East start at top-right, etc.)
  width: number;  // cm
  height: number; // cm
  sillHeight?: number; // cm from floor (for windows)
  doorSwing?: DoorSwing;
  swingClearance?: number; // cm radius of swing arc (defaults to door width)
}

export type FloorType = 
  | 'hardwood_oak' 
  | 'hardwood_walnut' 
  | 'herringbone_parquet' 
  | 'polished_concrete' 
  | 'limestone_tile' 
  | 'terrazzo';

export interface RoomMaterialFinish {
  wallColor: string; // hex (e.g. #F5F2EB for warm alabaster)
  wallFinish: 'matte' | 'satin' | 'limewash';
  floorType: FloorType;
  floorColor: string; // hex
}

export interface DesignVariant {
  id: string;
  name: string;
  furniture: FurnitureItem[];
  finishes: RoomMaterialFinish;
  createdAt: string;
}

export type RoomType = 
  | 'living' 
  | 'bedroom' 
  | 'kitchen' 
  | 'dining' 
  | 'office' 
  | 'bathroom' 
  | 'hallway' 
  | 'balcony' 
  | 'other';

export interface RoomModel {
  id: string;
  name: string;
  type: RoomType;
  floorId: string;
  width: number;   // cm (X dimension, West-to-East)
  length: number;  // cm (Y dimension, North-to-South)
  height: number;  // cm (Z dimension, floor to ceiling)
  wallThickness: number; // cm (default 15cm)
  openings: RoomOpening[];
  furniture: FurnitureItem[];
  finishes: RoomMaterialFinish;
  variants?: DesignVariant[];
  activeVariantId?: string;
}

export interface FloorModel {
  id: string;
  name: string;
  level: number; // 0 = Ground Floor, 1 = First Floor, -1 = Basement, etc.
}

export interface PhotoDetectionSuggestion {
  id: string;
  label: string;
  category: FurnitureItem['category'];
  estimatedWidth: number;  // cm
  estimatedDepth: number;  // cm
  estimatedHeight: number; // cm
  suggestedX: number;      // cm
  suggestedY: number;      // cm
  rotation: number;        // degrees
  confidence: number;      // 0.0 - 1.0
  color: string;
  modelType: string;
  box2D?: {
    x: number;      // normalized 0..1 in photo
    y: number;
    width: number;
    height: number;
  };
  notes?: string;
}

export interface PhotoContext {
  hasPhoto: boolean;
  photoDataUrl?: string; // Stored locally only, never transmitted
  photoName?: string;
  uploadedAt?: string;
  imageDimensions?: { width: number; height: number };
  detectedSuggestions?: PhotoDetectionSuggestion[];
  privacyConsentAcknowledged: boolean;
}

export type AiProviderType = 
  | 'local-heuristic' 
  | 'local-gemma'
  | 'local-ollama' 
  | 'cloud-gemini' 
  | 'custom-gemini-key' 
  | 'disabled';

export interface AppSettings {
  displayUnit: UnitType;
  gridSnap: boolean;
  gridSnapSizeCm: number; // e.g., 5 or 10 cm
  showClearanceZones: boolean;
  showDimensionsOnPlan: boolean;
  enableExternalAi: boolean; // Explicit user opt-in required for cloud AI
  aiProvider: AiProviderType;
  customAiApiKey?: string;
  ollamaBaseUrl?: string;    // e.g., 'http://localhost:11434'
  ollamaModel?: string;      // e.g., 'llama3.2-vision'
  gemmaModel?: string;       // e.g., 'paligemma:3b' or 'paligemma'
}

export interface HomeProject {
  id: string;
  name: string;
  tagline?: string;
  createdAt: string;
  updatedAt: string;
  floors: FloorModel[];
  rooms: RoomModel[];
  activeRoomId: string;
  activeFloorId: string;
  photoContext: PhotoContext;
  settings: AppSettings;
  // Legacy single-room compatibility accessors
  room?: RoomModel;
  furniture?: FurnitureItem[];
}

// Backward compatibility alias for existing modules
export type FitProject = HomeProject;

// Fit-report semantics (strict adherence to requirements)
export type FitStatus = 'PASS' | 'FAIL' | 'REVIEW' | 'NOT_CHECKED';

export type CheckCategory = 
  | 'room-boundary'
  | 'furniture-collision'
  | 'door-clearance'
  | 'functional-clearance'
  | 'measurement-confidence';

export interface SpatialCheckItem {
  id: string;
  title: string;
  description: string;
  category: CheckCategory;
  status: FitStatus;
  affectedItemIds: string[];
  severity: 'error' | 'warning' | 'info';
  details?: string;
  remedyRecommendation?: string;
}

// Backward-compatibility type alias
export type FitCheckItem = SpatialCheckItem;

export interface FitReport {
  overallStatus: FitStatus;
  generatedAt: string;
  summary: {
    passCount: number;
    failCount: number;
    reviewCount: number;
    notCheckedCount: number;
  };
  checks: SpatialCheckItem[];
  disclaimer: string;
}

export const MANDATORY_FIT_DISCLAIMER = 
  "Passing a room geometry check does not guarantee successful delivery, " +
  "installation, structural safety, or compliance with building codes. " +
  "Always measure physical delivery paths (stairwells, doorways, elevators) " +
  "and consult a professional for structural or safety modifications.";

export const DEFAULT_MATERIAL_FINISH: RoomMaterialFinish = {
  wallColor: '#F5F2EB', // Warm Alabaster
  wallFinish: 'matte',
  floorType: 'hardwood_oak',
  floorColor: '#C49A6C', // Warm Natural Oak
};
